spring:
  application:
    name: eureka-client

# eureka 配置
eureka:
  client:
    service-url:
      # defaultZone 在` Eureka 客户端配置`中，可向（一个或多个）` Eureka 服务器 `注册
      # defaultZone 是个map，默认值为 http://localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka
