spring:
  application:
    name: eureka-client

# eureka 配置
eureka:
  instance:
  # 该属性用在 Client 端，设置为 true，则表示使用IP向注册中心注册；否则使用主机名注册。默认值为 false
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://192.168.0.107:8761/eureka
